AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bitcoin-indicator-alert

Globals:
  Function:
    Timeout: !Ref FunctionTimeout
    MemorySize: !Ref FunctionMemorySize
    Handler: app.lambda_handler
    Runtime: python3.9
    Architectures:
      - x86_64

Parameters:
  SNSEmailParameter:
    Type: String
    Description: Enter email address for execution failure SNS topic subscription.
  Schedule:
    Type: String
    Description: Cron schedule for function invocation
    Default: cron(0 8 * * ? *)
  FunctionTimeout:
    Type: Number
    Description: Lambda function timeout
    Default: 600
  FunctionMemorySize:
    Type: Number
    Description: Lambda function memory size
    Default: 500
  EmailSecretBucket:
    Type: String
    Description: S3 bucket that contains email secrets
  EmailSecretJsonKey:
    Type: String
    Description: JSON file that contains email secrets
  ApiSecretBucket:
    Type: String
    Description: S3 bucket that contains API secrets
  ApiSecretJsonKey:
    Type: String
    Description: JSON file that contains API secrets

Resources:
  BitcoinIndicatorAlertFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bitcoin-indicator-alert/
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref EmailSecretBucket
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: !Ref Schedule
            Name: BitcoinIndicatorAlertSchedule
            Description: Calculates bitcoin indicator metrics and sends email alerts when thresholds are triggered.
            Enabled: true
            Input: !Sub 
              - '{"email_secret_bucket": "${EmailSecretBucket}", "email_secret_json_key": "${EmailSecretJsonKey}", "api_secret_bucket": "${ApiSecretBucket}", "api_secret_json_key": "${ApiSecretJsonKey}"}'
              - EmailSecretBucket: !Ref EmailSecretBucket
                EmailSecretJsonKey: !Ref EmailSecretJsonKey
                ApiSecretBucket: !Ref ApiSecretBucket
                ApiSecretJsonKey: !Ref ApiSecretJsonKey

  BitcoinIndicatorAlertErrorTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: !Ref SNSEmailParameter
        Protocol: email
  
  ExecutionFailureAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      ActionsEnabled: true
      AlarmDescription: 'Sends an alarm when the Bitcoin Indicator Alert lambda function fails.'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
         - Name: FunctionName
           Value: !Ref BitcoinIndicatorAlertFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 21600
      Threshold: 1
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref BitcoinIndicatorAlertErrorTopic

Outputs:
  BitcoinIndicatorAlertFunction:
    Description: "Bitcoin Indicator Alert Function ARN"
    Value: !GetAtt BitcoinIndicatorAlertFunction.Arn
  BitcoinIndicatorAlertIamRole:
    Description: "Implicit IAM Role created for Bitcoin Indicator Alert function"
    Value: !GetAtt BitcoinIndicatorAlertFunctionRole.Arn
